---
name: Deploy dev branch to Firebase Hosting on merge
on:
  push:
    branches:
      - dev
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "12"
          cache: "npm"
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          # Workaround for react-pdf build warnings
          CI: false
          EXTEND_ESLINT: true
          REACT_APP_FIREBASE_API_KEY: "${{ secrets.WHATBOARD_DEV_FIREBASE_API_KEY }}"
          REACT_APP_FIREBASE_AUTH_DOMAIN: "${{ secrets.WHATBOARD_DEV_FIREBASE_AUTH_DOMAIN }}"
          REACT_APP_FIREBASE_DATABASE_URL: "${{ secrets.WHATBOARD_DEV_FIREBASE_DATABASE_URL }}"
          REACT_APP_FIREBASE_PROJECT_ID: "${{ secrets.WHATBOARD_DEV_FIREBASE_PROJECT_ID }}"
          REACT_APP_FIREBASE_STORAGE_BUCKET: "${{ secrets.WHATBOARD_DEV_FIREBASE_STORAGE_BUCKET }}"
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: "${{ secrets.WHATBOARD_DEV_FIREBASE_MESSAGING_SENDER_ID }}"
          REACT_APP_FIREBASE_APP_ID: "${{ secrets.WHATBOARD_DEV_FIREBASE_APP_ID }}"
          REACT_APP_FIREBASE_MEASUREMENT_ID: "${{ secrets.WHATBOARD_DEV_FIREBASE_MEASUREMENT_ID }}"
          REACT_APP_IFRAMELY_API_KEY: "${{ secrets.WHATBOARD_DEV_IFRAMELY_API_KEY }}"
          REACT_APP_STRIPE_PUBLISHABLE_KEY: "${{ secrets.WHATBOARD_DEV_STRIPE_PUBLISHABLE_KEY }}"
          REACT_APP_RECAPTCHA_ENTERPRISE_SITE_KEY: "${{ secrets.WHATBOARD_DEV_RECAPTCHA_ENTERPRISE_SITE_KEY }}"
          REACT_APP_SENTRY_ENABLED: false
          REACT_APP_SENTRY_ENVIRONMENT: "development"
          REACT_APP_SENTRY_RELEASE: "${{ github.sha }}"
          REACT_APP_SENTRY_DEBUG: false
      - name: Archive Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "12"
          cache: "npm"
          cache-dependency-path: |
            package.json
            functions/package.json
      - name: Install Dependencies
        run: npm install && cd functions && npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v2.1.0
        with:
          args: deploy --force
        env:
          GCP_SA_KEY: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_WHATBOARD_DEV }}"
          PROJECT_ID: "${{ secrets.WHATBOARD_DEV_FIREBASE_PROJECT_ID }}"
